import "../../app/global.css"; 
import AdminLayoutClient from "./AdminLayoutClient";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "@ant-design/v5-patch-for-react-19";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="vi">
      <body>
        <AdminLayoutClient>{children}</AdminLayoutClient>

        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
